module.exports.config = {
  name: "dpz",
  version: '1.0.0',
  hasPermision: 0,
  credit: '𝙉𝙖𝙪𝙜𝙝𝙩𝙮 𝘽𝙧𝙖𝙣𝙙',
  description: 'random  pics',
  commandCategory: 'random-img',
  cooldowns: 0,
}
module.exports.run = async function ({
  api,
  event,
  args,
  utils,
  Users,
  Threads,
}) {
  const axios = require('axios')
  const request = require('request')
  const fs = require('fs-extra')
  var link = ["https://i.imgur.com/ZoqvvOi.jpegZoqvvOi",
"https://i.imgur.com/A6Jl04m.jpeg",
"https://i.imgur.com/7Hwe6e5.jpeg",
"https://i.imgur.com/vqM2JLg.jpeg",
"https://i.imgur.com/IeTvGDe.jpeg", 
"https://i.imgur.com/IeTvGDe.jpeg",
"https://i.imgur.com/9qZBair.jpeg", 
"https://i.imgur.com/DN3ixV8.jpeg",
"https://i.imgur.com/qyDe7er.jpeg",
"https://i.imgur.com/qyDe7er.jpeg",
"https://i.imgur.com/DCDNg59.jpeg", 
"https://i.imgur.com/WGPrB0t.jpeg", 
"https://i.imgur.com/vJr5IAs.jpeg",
"https://i.imgur.com/yIxTLmE.jpeg",
"https://i.imgur.com/cHh3I9J.jpeg",
"https://i.imgur.com/PRK6lQI.jpeg", 
"https://i.imgur.com/ckk6m3D.jpeg ",
"https://i.imgur.com/okF9jnh.jpeg", 
"https://i.imgur.com/Cobhpm9.jpeg",             "https://i.imgur.com/PHSobNq.jpeg",
"https://i.imgur.com/VhRcn1A.jpeg",
"https://i.imgur.com/xE0JrtD.jpeg", 
"https://i.imgur.com/FwyOkGK.jpeg", 
"https://i.imgur.com/wlXyFmr.jpeg",
"https://i.imgur.com/7uAOPXW.jpeg", 
"https://i.imgur.com/hYVZUMv.jpeg", 
"https://i.imgur.com/e25iCgb.jpeg", 
"https://i.imgur.com/qtEv3JZ.jpeg", 
"https://i.imgur.com/SIiMs1m.jpeg",
"https://i.imgur.com/KsgK8YQ.jpeg", 
"https://i.imgur.com/QYX3bBl.jpeg",
"https://i.imgur.com/ee4KejT.jpeg", 
"https://i.imgur.com/W5mqzKL.jpeg", 
"https://i.imgur.com/UXKl4nY.jpeg",
"https://i.imgur.com/5CRoCUQ.jpeg", 
"https://i.imgur.com/jtz8lMe.jpeg",
"https://i.imgur.com/oAuICkv.jpeg",
"https://i.imgur.com/Ctlcy5I.jpeg", 
"https://i.imgur.com/skApQbD.jpeg", 
"https://i.imgur.com/Wtwb4hy.jpeg",
"https://i.imgur.com/ELWHbX5.jpeg", 
"https://i.imgur.com/5oZMQMq.jpeg", 
"https://i.imgur.com/fxT3mPT.jpeg",
"https://i.imgur.com/ZxilNdq.jpeg", 
"https://i.imgur.com/Pqe6c8R.jpeg", 
"https://i.imgur.com/euIOXWj.jpeg",
"https://i.imgur.com/f9xKTgo.jpeg",
"https://i.imgur.com/X4t44E9.jpeg",
"https://i.imgur.com/tm5gqaA.jpeg",
"https://i.imgur.com/fikIOlz.jpeg",
"https://i.imgur.com/GgNWHE5.jpeg",
"https://i.imgur.com/5r1Mmqh.jpeg",
"https://i.imgur.com/lAkcOBD.jpeg",
"https://i.imgur.com/A6qMMBp.jpeg",
"https://i.imgur.com/SWorCHL.jpeg",
"https://i.imgur.com/4xT4kNS.jpeg",
"",
"https://i.imgur.com/nTYXaHk.jpeg",
"https://i.imgur.com/rCp3wIf.jpeg",
"https://i.imgur.com/A3Cxd9F.jpeg",
"https://i.imgur.com/TXGROEy.jpeg",
"https://i.imgur.com/IGXp5Gn.jpeg",
"https://i.imgur.com/g6bIvxr.jpeg",
"https://i.imgur.com/1iXWGTi.jpeg",
"https://i.imgur.com/F042Rkn.jpeg",
"https://i.imgur.com/XNYtRjE.jpeg",
"https://i.imgur.com/fbRItb6.jpeg",
"https://i.imgur.com/JgQJFeS.jpeg",
"https://i.imgur.com/gVGzGXE.jpeg",
"https://i.imgur.com/ULjnSTO.jpeg",
"https://i.imgur.com/s9sbcKh.jpeg",
"https://i.imgur.com/fjCbCEt.jpeg",
"https://i.imgur.com/RswDc0f.jpeg",
"https://i.imgur.com/PWu5RQ3.jpeg",
"https://i.imgur.com/sQnU14w.jpeg",
"https://i.imgur.com/ideCsdq.jpeg",
"https://i.imgur.com/y5tiCxV.jpeg",
"https://i.imgur.com/KS5fXp4.jpeg",
"https://i.imgur.com/XxNxrBn.jpeg",
"https://i.imgur.com/VnLZIYi.jpeg",
"https://i.imgur.com/UHeLnIY.jpeg",
"https://i.imgur.com/n6lR6Zv.jpeg",
"https://i.imgur.com/xSM8ZIs.jpeg",
"https://i.imgur.com/jDFLdr7.jpeg",
"https://i.imgur.com/pHleRId.jpeg",
"https://i.imgur.com/KRfhEVk.jpeg",
"https://i.imgur.com/TTsBnlb.jpeg",
"https://i.imgur.com/LfudwI3.jpeg",
"https://i.imgur.com/T3tlxXU.jpeg",
"https://i.imgur.com/MaLETLq.jpeg",
"https://i.imgur.com/wUo6r0g.jpeg",
"https://i.imgur.com/tzELVh7.jpeg",
"https://i.imgur.com/9yQp0dA.jpeg",
"https://i.imgur.com/YqcJ1hZ.jpeg",
"https://i.imgur.com/snN36Pd.jpeg",
"https://i.imgur.com/mv5DT2h.jpeg",
"https://i.imgur.com/pnaKd3x.jpeg",
"https://i.imgur.com/u0A1Eoz.jpeg",
"https://i.imgur.com/7ME7ZZf.jpeg",
"https://i.imgur.com/uFtykWU.jpeg",
"https://i.imgur.com/PIftsQ0.jpeg",
"https://i.imgur.com/aUCV0vV.jpeg",
"https://i.imgur.com/7sizNvy.jpeg",
"https://i.imgur.com/8pNm2WX.jpeg",
"https://i.imgur.com/AC9660t.jpeg",
"https://i.imgur.com/GVNZGb4.jpeg",
"https://i.imgur.com/GfVtOOr.jpeg",
"https://i.imgur.com/R9TphxO.jpeg",
"https://i.imgur.com/DsdMFiC.jpeg",
"https://i.imgur.com/rUiHvnf.jpeg",
"https://i.imgur.com/blKk3om.jpeg",
"https://i.imgur.com/Y7GXVol.jpeg",
"https://i.imgur.com/ToQE1vT.jpeg",
"https://i.imgur.com/9vQodaN.jpeg",
"https://i.imgur.com/kpfILn4.jpeg",
"https://i.imgur.com/JxjDCYD.jpeg",
"https://i.imgur.com/CEg3GCT.jpeg",
"https://i.imgur.com/ulS6c0f.jpeg",
"https://i.imgur.com/9ZaP5J5.jpeg",
"https://i.imgur.com/y0z2uAq.jpeg",
"https://i.imgur.com/Oit2IB6.jpeg",
"https://i.imgur.com/aAWjNzq.jpeg",
"https://i.imgur.com/vKnAQZc.jpeg",
"https://i.imgur.com/bXjnHGj.jpeg",
"https://i.imgur.com/nBZ7PNK.jpeg",
"https://i.imgur.com/bS6J0pU.jpeg",
"https://i.imgur.com/UTw3GL0.jpeg",
"https://i.imgur.com/dtp1Lf6.jpeg",
"https://i.imgur.com/uaAQl4T.jpeg",
"https://i.imgur.com/Fid9YTZ.jpeg",
"https://i.imgur.com/pYZLNVX.jpeg",
"https://i.imgur.com/M5B2HHU.jpeg",
"https://i.imgur.com/f39tBjG.jpeg",
"https://i.imgur.com/82m8rTA.jpeg",
"https://i.imgur.com/BgFr7CY.jpeg",
"https://i.imgur.com/yW71eVo.jpeg",
"https://i.imgur.com/owsDo6V.jpeg",
"https://i.imgur.com/dDH6tDR.jpeg",
"https://i.imgur.com/ukMzDeV.jpeg",
"https://i.imgur.com/iAWwtrH.jpeg",
"https://i.imgur.com/lqLaLFw.jpeg",
"https://i.imgur.com/y2wsbLs.jpeg",
"https://i.imgur.com/FUIZkzA.jpeg",
"https://i.imgur.com/uOxMTY7.jpeg",
"https://i.imgur.com/wCdU250.jpeg",
"https://i.imgur.com/gQm98W6.jpeg"];
  var Naughty = ['༺═─────────────═༻\n            𝙉𝙖𝙪𝙜𝙝𝙩𝙮 𝘽𝙧𝙖𝙣𝙙\n༺═─────────────═༻'],
    juswa1 = Naughty[Math.floor(Math.random() * Naughty.length)],
    callback = () =>
      api.sendMessage(
        {
          body: '' + juswa1,
          attachment: fs.createReadStream(__dirname + '/cache/zac.jpeg'),
        },
        event.threadID,
        () => fs.unlinkSync(__dirname + '/cache/zac.jpeg')
      )
  return request(encodeURI(link[Math.floor(Math.random() * link.length)]))
    .pipe(fs.createWriteStream(__dirname + '/cache/zac.jpeg'))
    .on('close', () => callback())
  }